apiVersion: v1
kind: Service
metadata:
  labels:
    service: dongfeng-attendance
  namespace: dongfeng-back
  name: dongfeng-attendance
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55551
    targetPort: 0
  selector:    
    app: dongfeng-attendance