apiVersion: apps/v1
kind: Deployment
metadata:  
  labels:
    deployment: dongfeng-attendance
  namespace: dongfeng-back
  name: dongfeng-attendance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dongfeng-attendance
  template:
    metadata:      
      labels:
        app: dongfeng-attendance
    spec:      
      containers:
      - name: dongfeng-attendance        
        image: ilovelili/dongfeng-attendance:latest
        imagePullPolicy: Always
        command: [
          "./server",
        ]
        env:
        - name: MICRO_REGISTRY
          value: kubernetes
        - name: DF_ENVIROMENT
          value: dev
        - name: MICRO_SERVER_ADDRESS
          value: 0.0.0.0:9091
        ports:
          - containerPort: 9091
        resources:
          limits:
            memory: "128Mi"
            cpu: "1000m"
      - name: liveness
        command: [
          "/health",
          "--health_address=0.0.0.0:8080",
          "--server_name=dongfeng.svc.attendance.server.api",
          "--server_address=0.0.0.0:9091",
        ]
        image: ilovelili/micro-health:latest
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"