apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dongfeng-attendance
  namespace: dongfeng-back
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dongfeng-attendance
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70